name: "Check for new releases to syndicate to Bluesky"
on:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes
  workflow_dispatch:
env:
  PYTHONUNBUFFERED: 1 # ensure that python scripts live output instead of buffering

jobs:
  sync:
    name: Syndication
    timeout-minutes: 5
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Syndicate Beehive publications to Bluesky
        run: python hivesky.py
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          BROWSERLESS_API_TOKEN: ${{ secrets.BROWSERLESS_API_TOKEN }}
          BROWSERLESS_URL: ${{ secrets.BROWSERLESS_URL }}
          POST_TO_BLUESKY: True
      - name: Commit history changes
        # Even if we crash out, we can persist our state so that the next run
        # will catch anything that fell over
        if: always()
        run: |
          set -eux

          git config --local user.email "helper@utf9k.net"
          git config --local user.name "Helper Bot"

          if [ -z "$(git status --porcelain)" ]; then
            # No changes have occurred so there's no point generating a commit"
            exit 0
          fi
          
          git add .
          git commit -m "New releases have been syndicated"
          git push
